### ISSUE TITLE
Ropro shenanigans

### ISSUE THREAD

**Issue by TheConfusedlol** [SuppliedOrange/obcb-contraptions#1]
hey there @SuppliedOrange, i was looking through the old ropro-cracked thread where i saw you fixed the proxy problem seemingly simply. Apologies' for making this an issue under a completely unrelated project but I had no proper way of contacting you. If you are willing to explain how you fixed it, I'd be glad to hear it.

**Comment by SuppliedOrange** [comment]
Hi, my method is no longer viable. That is why I have privated the repo. Stefanuk's version still worked when I made that issue.

**Comment by TheConfusedlol** [comment]
> Hi, my method is no longer viable. That is why I have privated the repo. Stefanuk's version still worked when I made that issue.

Ah, i see. Thanks for the reply!
